// protoc --go_out=. --go-grpc_out=. proto/order_service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/order_service.proto

package order_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------DATA----------
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     //what user placed this order?
	VendorId      string                 `protobuf:"bytes,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`               //who is this order for?
	Items         []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`                                     //what items is in this order
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                   //just created
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`            //when did this order get placed?
	DropoffLocId  string                 `protobuf:"bytes,7,opt,name=dropoff_loc_id,json=dropoffLocId,proto3" json:"dropoff_loc_id,omitempty"` //where does user want robot to drop off?
	RobotId       string                 `protobuf:"bytes,8,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetDropoffLocId() string {
	if x != nil {
		return x.DropoffLocId
	}
	return ""
}

func (x *Order) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *OrderItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// --------REQUESTS-------
type InsertOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertOrderRequest) Reset() {
	*x = InsertOrderRequest{}
	mi := &file_proto_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOrderRequest) ProtoMessage() {}

func (x *InsertOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOrderRequest.ProtoReflect.Descriptor instead.
func (*InsertOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *InsertOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_proto_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// ---------RESPONSES----------
type InsertOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	ReturnMsg     string                 `protobuf:"bytes,2,opt,name=return_msg,json=returnMsg,proto3" json:"return_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertOrderResponse) Reset() {
	*x = InsertOrderResponse{}
	mi := &file_proto_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOrderResponse) ProtoMessage() {}

func (x *InsertOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOrderResponse.ProtoReflect.Descriptor instead.
func (*InsertOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *InsertOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *InsertOrderResponse) GetReturnMsg() string {
	if x != nil {
		return x.ReturnMsg
	}
	return ""
}

type DeleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnMsg     string                 `protobuf:"bytes,1,opt,name=return_msg,json=returnMsg,proto3" json:"return_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderResponse) Reset() {
	*x = DeleteOrderResponse{}
	mi := &file_proto_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderResponse) ProtoMessage() {}

func (x *DeleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteOrderResponse) GetReturnMsg() string {
	if x != nil {
		return x.ReturnMsg
	}
	return ""
}

var File_proto_order_service_proto protoreflect.FileDescriptor

const file_proto_order_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/order_service.proto\x12\rorder_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tvendor_id\x18\x03 \x01(\tR\bvendorId\x12.\n" +
	"\x05items\x18\x04 \x03(\v2\x18.order_service.OrderItemR\x05items\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12$\n" +
	"\x0edropoff_loc_id\x18\a \x01(\tR\fdropoffLocId\x12\x19\n" +
	"\brobot_id\x18\b \x01(\tR\arobotId\"s\n" +
	"\tOrderItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"@\n" +
	"\x12InsertOrderRequest\x12*\n" +
	"\x05order\x18\x01 \x01(\v2\x14.order_service.OrderR\x05order\"@\n" +
	"\x12DeleteOrderRequest\x12*\n" +
	"\x05order\x18\x01 \x01(\v2\x14.order_service.OrderR\x05order\"`\n" +
	"\x13InsertOrderResponse\x12*\n" +
	"\x05order\x18\x01 \x01(\v2\x14.order_service.OrderR\x05order\x12\x1d\n" +
	"\n" +
	"return_msg\x18\x02 \x01(\tR\treturnMsg\"4\n" +
	"\x13DeleteOrderResponse\x12\x1d\n" +
	"\n" +
	"return_msg\x18\x01 \x01(\tR\treturnMsg2\xba\x01\n" +
	"\fOrderHandler\x12T\n" +
	"\vInsertOrder\x12!.order_service.InsertOrderRequest\x1a\".order_service.InsertOrderResponse\x12T\n" +
	"\vDeleteOrder\x12!.order_service.DeleteOrderRequest\x1a\".order_service.DeleteOrderResponseB\x16Z\x14/proto;order_serviceb\x06proto3"

var (
	file_proto_order_service_proto_rawDescOnce sync.Once
	file_proto_order_service_proto_rawDescData []byte
)

func file_proto_order_service_proto_rawDescGZIP() []byte {
	file_proto_order_service_proto_rawDescOnce.Do(func() {
		file_proto_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_service_proto_rawDesc), len(file_proto_order_service_proto_rawDesc)))
	})
	return file_proto_order_service_proto_rawDescData
}

var file_proto_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_order_service_proto_goTypes = []any{
	(*Order)(nil),                 // 0: order_service.Order
	(*OrderItem)(nil),             // 1: order_service.OrderItem
	(*InsertOrderRequest)(nil),    // 2: order_service.InsertOrderRequest
	(*DeleteOrderRequest)(nil),    // 3: order_service.DeleteOrderRequest
	(*InsertOrderResponse)(nil),   // 4: order_service.InsertOrderResponse
	(*DeleteOrderResponse)(nil),   // 5: order_service.DeleteOrderResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_order_service_proto_depIdxs = []int32{
	1, // 0: order_service.Order.items:type_name -> order_service.OrderItem
	6, // 1: order_service.Order.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: order_service.InsertOrderRequest.order:type_name -> order_service.Order
	0, // 3: order_service.DeleteOrderRequest.order:type_name -> order_service.Order
	0, // 4: order_service.InsertOrderResponse.order:type_name -> order_service.Order
	2, // 5: order_service.OrderHandler.InsertOrder:input_type -> order_service.InsertOrderRequest
	3, // 6: order_service.OrderHandler.DeleteOrder:input_type -> order_service.DeleteOrderRequest
	4, // 7: order_service.OrderHandler.InsertOrder:output_type -> order_service.InsertOrderResponse
	5, // 8: order_service.OrderHandler.DeleteOrder:output_type -> order_service.DeleteOrderResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_order_service_proto_init() }
func file_proto_order_service_proto_init() {
	if File_proto_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_service_proto_rawDesc), len(file_proto_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_service_proto_goTypes,
		DependencyIndexes: file_proto_order_service_proto_depIdxs,
		MessageInfos:      file_proto_order_service_proto_msgTypes,
	}.Build()
	File_proto_order_service_proto = out.File
	file_proto_order_service_proto_goTypes = nil
	file_proto_order_service_proto_depIdxs = nil
}
