package db

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strconv"

	"github.com/joho/godotenv"
	supabase "github.com/supabase-community/supabase-go"
	"golang.org/x/crypto/bcrypt"
)

type Database struct {
	client *supabase.Client
}

func New() *Database {
	godotenv.Load(".env")
	url := os.Getenv("SUPABASE_URL")
	apiKey := os.Getenv("SUPABASE_SECRET_KEY")
	client, err := supabase.NewClient(url, apiKey, nil)
	if err != nil {
		panic(fmt.Sprintf("db.New: failed to create supabase client: %v", err))
	}
	return &Database{client: client}
}

// Coordinate Type Enum
// 1 = Vendor
// 2 = Dropoff
// 3 = Waypoint

type CoordinateType int16

const (
	CoordinateTypeVendor   CoordinateType = 1
	CoordinateTypeDropoff  CoordinateType = 2
	CoordinateTypeWaypoint CoordinateType = 3
)

type Coordinate struct {
	ID   string         `json:"id"`
	Name string         `json:"name"`
	X    int            `json:"x"`
	Y    int            `json:"y"`
	Meta interface{}    `json:"meta"`
	Type CoordinateType `json:"type"`
}

type OrderItem struct {
	ID       string  `json:"id"`
	OrderID  int64   `json:"orderId"`
	ItemName string  `json:"itemName"`
	Quantity int     `json:"quantity"`
	Price    float64 `json:"price"`
}

type Order struct {
	ID              int64       `json:"id"`
	UserID          string      `json:"userId"`
	VendorID        string      `json:"vendorId"`
	Status          string      `json:"status"`
	CreatedAt       string      `json:"createdAt"`
	RobotID         string      `json:"robotId"`
	DropOffLocation string      `json:"dropOffLocation"`
	OrderItems      []OrderItem `json:"orderItems"`
}

type Robot struct {
	ID         string `json:"id"`
	Status     int    `json:"status"`
	LastUpdate string `json:"lastUpdate"`
	CurrentLoc string `json:"currentLoc"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	PhoneNum string `json:"phoneNum"`
	Password string `json:"password"`
}

type Vendor struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Address     string      `json:"address"`
	Hours       interface{} `json:"hours"`
	Coordinates string      `json:"coordinates"`
}

//questions: meta type for coordinate? list coordinates by type? what are all robot statuses

//----------------- Coordinate CRUD -----------------

// insert coordinate of some place of interest (vendor, dropoff, or waypoint)
//
// @param c: coordinate to insert
// @return error
func (db *Database) InsertCoordinate(ctx context.Context, c Coordinate) error {
	data := map[string]interface{}{
		"x":    c.X,
		"y":    c.Y,
		"name": c.Name,
		"meta": c.Meta,
		"type": c.Type,
	}

	_, _, err := db.client.From("coordinates").Insert(data, false, "", "", "").Execute()
	if err != nil {
		return fmt.Errorf("InsertCoordinate: %w", err)
	}

	return nil
}

// retrieve coordinate by uuid
//
// @param id: coordinate uuid
// @return coordinate, error
func (db *Database) GetCoordinate(ctx context.Context, id string) (Coordinate, error) {
	res, _, err := db.client.From("coordinates").Select("*", "exact", false).Eq("id", id).Execute()
	if err != nil {
		return Coordinate{}, fmt.Errorf("GetCoordinate: %w", err)
	}

	var coordinates []Coordinate
	if err := json.Unmarshal(res, &coordinates); err != nil {
		return Coordinate{}, fmt.Errorf("GetCoordinate unmarshal: %w", err)
	}
	if len(coordinates) == 0 {
		return Coordinate{}, fmt.Errorf("GetCoordinate: coordinate %s not found", id)
	}

	return coordinates[0], nil
}

// retrieve all coordinates
//
// @return list of coordinates, error
func (db *Database) ListCoordinates(ctx context.Context) ([]Coordinate, error) {
	res, _, err := db.client.From("coordinates").Select("*", "exact", false).Execute()
	if err != nil {
		return nil, fmt.Errorf("ListCoordinates: %w", err)
	}

	var coordinates []Coordinate
	if err := json.Unmarshal(res, &coordinates); err != nil {
		return nil, fmt.Errorf("ListCoordinates unmarshal: %w", err)
	}
	return coordinates, nil
}

// delete coordinate by uuid
//
// @param id: coordinate uuid
// @return error
func (db *Database) DeleteCoordinate(ctx context.Context, id string) error {
	_, _, err := db.client.From("coordinates").Delete("minimal", "").Eq("id", id).Execute()
	if err != nil {
		return fmt.Errorf("DeleteCoordinate: %w", err)
	}
	return nil
}

//----------------- Order CRUD -----------------

// insert order into database
//
// @param o: order with info from client
// @return error
func (db *Database) CreateOrder(ctx context.Context, o Order) error {
	data := map[string]interface{}{
		"userId":          o.UserID,
		"vendorId":        o.VendorID,
		"status":          o.Status,
		"dropOffLocation": o.DropOffLocation,
	}

	//id and createdAt are auto generated by database,
	//robotId starts as null and is only updated when assigned to a robot,
	//order items are inserted separately after order creation since they require the order ID

	res, _, err := db.client.From("orders").Insert(data, false, "", "representation", "").Execute()
	if err != nil {
		return fmt.Errorf("CreateOrder: %w", err)
	}

	//retrive the order and its id
	var insertedOrders []Order
	if err := json.Unmarshal(res, &insertedOrders); err != nil {
		return fmt.Errorf("CreateOrder unmarshal: %w", err)
	}
	if len(insertedOrders) == 0 {
		return fmt.Errorf("CreateOrder: no order returned after insert")
	}

	orderID := insertedOrders[0].ID

	// Insert all items associated with the order
	for _, item := range o.OrderItems {
		item.OrderID = orderID

		err := db.AddOrderItem(ctx, item)
		if err != nil {
			return fmt.Errorf("CreateOrder: failed to add order item: %w", err)
		}
	}

	return nil
}

// retrieve order by id
//
// @param id: order id
// @return order, error
func (db *Database) GetOrder(ctx context.Context, id int64) (Order, error) {
	res, _, err := db.client.From("orders").Select("*", "exact", false).Eq("id", strconv.FormatInt(id, 10)).Execute()
	if err != nil {
		return Order{}, fmt.Errorf("GetOrder: %w", err)
	}

	var orders []Order
	if err := json.Unmarshal(res, &orders); err != nil {
		return Order{}, fmt.Errorf("GetOrder unmarshal: %w", err)
	}
	if len(orders) == 0 {
		return Order{}, fmt.Errorf("GetOrder: order %d not found", id)
	}
	return orders[0], nil
}

// retrieve all orders for a specific user
//
// @param userID: user uuid
// @return list of orders, error
func (db *Database) ListOrdersByUser(ctx context.Context, userID string) ([]Order, error) {
	res, _, err := db.client.From("orders").Select("*", "exact", false).Eq("userId", userID).Execute()
	if err != nil {
		return nil, fmt.Errorf("ListOrdersByUser: %w", err)
	}

	var orders []Order
	if err := json.Unmarshal(res, &orders); err != nil {
		return nil, fmt.Errorf("ListOrdersByUser unmarshal: %w", err)
	}
	return orders, nil
}

// retrieve all orders for a specific vendor
//
// @param vendorID: vendor uuid
// @return list of orders, error
func (db *Database) ListOrdersByVendor(ctx context.Context, vendorID string) ([]Order, error) {
	res, _, err := db.client.From("orders").Select("*", "exact", false).Eq("vendorId", vendorID).Execute()
	if err != nil {
		return nil, fmt.Errorf("ListOrdersByVendor: %w", err)
	}

	var orders []Order
	if err := json.Unmarshal(res, &orders); err != nil {
		return nil, fmt.Errorf("ListOrdersByVendor unmarshal: %w", err)
	}
	return orders, nil
}

// update order status (e.g. "pending", "in_progress", "completed")
//
// @param id: order id
// @param status: new order status
// @return error
func (db *Database) UpdateOrderStatus(ctx context.Context, id int64, status string) error {
	data := map[string]interface{}{"status": status}

	_, _, err := db.client.From("orders").Update(data, "", "").Eq("id", strconv.FormatInt(id, 10)).Execute()
	if err != nil {
		return fmt.Errorf("UpdateOrderStatus: %w", err)
	}
	return nil
}

// assign order to robot by updating robotId field of order
//
// @param orderID: order id
// @param robotID: robot uuid
// @return error
func (db *Database) AssignOrderToRobot(ctx context.Context, orderID int64, robotID string) error {
	data := map[string]interface{}{"robotId": robotID}

	_, _, err := db.client.From("orders").Update(data, "", "").Eq("id", strconv.FormatInt(orderID, 10)).Execute()
	if err != nil {
		return fmt.Errorf("AssignOrderToRobot: %w", err)
	}
	return nil
}

func (db *Database) DeleteOrder(ctx context.Context, id int64) error {
	_, _, err := db.client.From("orders").Delete("minimal", "").Eq("id", strconv.FormatInt(id, 10)).Execute()
	if err != nil {
		return fmt.Errorf("DeleteOrder: %w", err)
	}
	return nil
}

/*

redundant? CreateOrder already expects order with orderItems and will add everything into orders and orderItems tables in one call.

func (db *Database) CreateOrderWithItems(ctx context.Context, order Order, items []OrderItem) error {
	if err := db.CreateOrder(ctx, order); err != nil {
		return fmt.Errorf("CreateOrderWithItems: failed to create order: %w", err)
	}

	for _, item := range items {
		if err := db.AddOrderItem(ctx, item); err != nil {
			return fmt.Errorf("CreateOrderWithItems: failed to add item: %w", err)
		}
	}
	return nil
}
*/

// add order item to orderItems table
//
// @param item: order item to add, must include OrderID to associate with correct order
// @return error
func (db *Database) AddOrderItem(ctx context.Context, item OrderItem) error {
	data := map[string]interface{}{
		"orderId":  item.OrderID,
		"itemName": item.ItemName,
		"quantity": item.Quantity,
		"price":    item.Price,
	}

	_, _, err := db.client.From("orderItems").Insert(data, false, "", "", "").Execute()
	if err != nil {
		return fmt.Errorf("AddOrderItem: %w", err)
	}
	return nil
}

// retrieve all items for a specific order
//
// @param orderID: order id
// @return list of order items, error
func (db *Database) GetOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error) {
	res, _, err := db.client.From("orderItems").Select("*", "exact", false).Eq("orderId", strconv.FormatInt(orderID, 10)).Execute()
	if err != nil {
		return nil, fmt.Errorf("GetOrderItems: %w", err)
	}

	var items []OrderItem
	if err := json.Unmarshal(res, &items); err != nil {
		return nil, fmt.Errorf("GetOrderItems unmarshal: %w", err)
	}
	return items, nil
}

// delete order item by id
//
// @param id: order item id
// @return error
func (db *Database) DeleteOrderItem(ctx context.Context, id string) error {
	_, _, err := db.client.From("orderItems").Delete("minimal", "").Eq("id", id).Execute()
	if err != nil {
		return fmt.Errorf("DeleteOrderItem: %w", err)
	}
	return nil
}

//----------------- Robot CRUD -----------------

// retrieve robot by id
//
// @param id: robot uuid
// @return robot, error
func (db *Database) GetRobot(ctx context.Context, id string) (Robot, error) {
	res, _, err := db.client.From("robots").Select("*", "exact", false).Eq("id", id).Execute()
	if err != nil {
		return Robot{}, fmt.Errorf("GetRobot: %w", err)
	}

	var robots []Robot
	if err := json.Unmarshal(res, &robots); err != nil {
		return Robot{}, fmt.Errorf("GetRobot unmarshal: %w", err)
	}
	if len(robots) == 0 {
		return Robot{}, fmt.Errorf("GetRobot: robot %s not found", id)
	}
	return robots[0], nil
}

// update robot status
//
// @param id: robot uuid
// @param status: new robot status
// @return error
func (db *Database) SetRobotStatus(ctx context.Context, id string, status int) error {
	data := map[string]interface{}{"status": status}
	_, _, err := db.client.From("robots").Update(data, "", "").Eq("id", id).Execute()
	if err != nil {
		return fmt.Errorf("SetRobotStatus: %w", err)
	}
	return nil
}

// update robot location by updating currentLoc field of robot
//
// @param id: robot uuid
// @param coordinateID: coordinate uuid of new robot location
// @return error
func (db *Database) UpdateRobotLocation(ctx context.Context, id string, coordinateID string) error {
	data := map[string]interface{}{"currentLoc": coordinateID}
	_, _, err := db.client.From("robots").Update(data, "", "").Eq("id", id).Execute()
	if err != nil {
		return fmt.Errorf("UpdateRobotLocation: %w", err)
	}
	return nil
}

// retrieve all robots
//
// @return list of robots, error
func (db *Database) ListRobots(ctx context.Context) ([]Robot, error) {
	res, _, err := db.client.From("robots").Select("*", "exact", false).Execute()
	if err != nil {
		return nil, fmt.Errorf("ListRobots: %w", err)
	}

	var robots []Robot
	if err := json.Unmarshal(res, &robots); err != nil {
		return nil, fmt.Errorf("ListRobots unmarshal: %w", err)
	}
	return robots, nil
}

// delete robot by uuid
//
// @param id: robot uuid
// @return error
func (db *Database) DeleteRobot(ctx context.Context, id string) error {
	_, _, err := db.client.From("robots").Delete("minimal", "").Eq("id", id).Execute()
	if err != nil {
		return fmt.Errorf("DeleteRobot: %w", err)
	}
	return nil
}

//----------------- User CRUD -----------------

func HashPassword(password string) (string, error) {
	// GenerateFromPassword automatically generates a random salt and includes it in the resulting hash
	bytes, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	return string(bytes), err
}

// insert user into database
//
// @param u: user to insert, must include name, email, phoneNum, and password fields (id is auto generated)
// @return error
func (db *Database) InsertUser(ctx context.Context, u User) error {
	hashedPassword, err := HashPassword(u.Password)
	if err != nil {
		return fmt.Errorf("InsertUser: %w", err)
	}

	data := map[string]interface{}{
		"name":     u.Name,
		"email":    u.Email,
		"phoneNum": u.PhoneNum,
		"password": hashedPassword,
	}

	_, _, err = db.client.From("users").Insert(data, false, "", "", "").Execute()
	if err != nil {
		return fmt.Errorf("InsertUser: %w", err)
	}
	return nil
}

// retrieve user by uuid
//
// @param id: user uuid
// @return user, error
func (db *Database) GetUser(ctx context.Context, id string) (User, error) {
	res, _, err := db.client.From("users").Select("*", "exact", false).Eq("id", id).Execute()
	if err != nil {
		return User{}, fmt.Errorf("GetUser: %w", err)
	}

	var users []User
	if err := json.Unmarshal(res, &users); err != nil {
		return User{}, fmt.Errorf("GetUser unmarshal: %w", err)
	}
	if len(users) == 0 {
		return User{}, fmt.Errorf("GetUser: user %s not found", id)
	}
	return users[0], nil
}

// retrieve all users
//
// @return list of users, error
func (db *Database) ListUsers(ctx context.Context) ([]User, error) {
	res, _, err := db.client.From("users").Select("*", "exact", false).Execute()
	if err != nil {
		return nil, fmt.Errorf("ListUsers: %w", err)
	}

	var users []User
	if err := json.Unmarshal(res, &users); err != nil {
		return nil, fmt.Errorf("ListUsers unmarshal: %w", err)
	}
	return users, nil
}

// delete user by uuid
//
// @param id: user uuid
// @return error
func (db *Database) DeleteUser(ctx context.Context, id string) error {
	_, _, err := db.client.From("users").Delete("minimal", "").Eq("id", id).Execute()
	if err != nil {
		return fmt.Errorf("DeleteUser: %w", err)
	}
	return nil
}

//----------------- Vendor CRUD -----------------

// insert vendor into database
//
// @param v: vendor to insert, must include name, address, hours, and coordinates (uuid) fields (id is auto generated)
// @return error
func (db *Database) InsertVendor(ctx context.Context, v Vendor) error {
	data := map[string]interface{}{
		"name":        v.Name,
		"address":     v.Address,
		"hours":       v.Hours,
		"coordinates": v.Coordinates,
	}

	_, _, err := db.client.From("vendors").Insert(data, false, "", "", "").Execute()
	if err != nil {
		return fmt.Errorf("InsertVendor: %w", err)
	}
	return nil
}

// retrieve vendor by uuid
//
// @param id: vendor uuid
// @return vendor, error
func (db *Database) GetVendor(ctx context.Context, id string) (Vendor, error) {
	res, _, err := db.client.From("vendors").Select("*", "exact", false).Eq("id", id).Execute()
	if err != nil {
		return Vendor{}, fmt.Errorf("GetVendor: %w", err)
	}

	var vendors []Vendor
	if err := json.Unmarshal(res, &vendors); err != nil {
		return Vendor{}, fmt.Errorf("GetVendor unmarshal: %w", err)
	}
	if len(vendors) == 0 {
		return Vendor{}, fmt.Errorf("GetVendor: vendor %s not found", id)
	}
	return vendors[0], nil
}

// retrieve all vendors
//
// @return list of vendors, error
func (db *Database) ListVendors(ctx context.Context) ([]Vendor, error) {
	res, _, err := db.client.From("vendors").Select("*", "exact", false).Execute()
	if err != nil {
		return nil, fmt.Errorf("ListVendors: %w", err)
	}

	var vendors []Vendor
	if err := json.Unmarshal(res, &vendors); err != nil {
		return nil, fmt.Errorf("ListVendors unmarshal: %w", err)
	}
	return vendors, nil
}

// delete vendor by uuid
//
// @param id: vendor uuid
// @return error
func (db *Database) DeleteVendor(ctx context.Context, id string) error {
	_, _, err := db.client.From("vendors").Delete("minimal", "").Eq("id", id).Execute()
	if err != nil {
		return fmt.Errorf("DeleteVendor: %w", err)
	}
	return nil
}
