// app/dashboard/[vendor]/page.tsx
"use client"
import { useParams, useRouter } from 'next/navigation'
import { useState } from 'react'

interface MenuItem {
  item_id: number;
  item_name: string;
  price: number;
  description: string;
}

interface OrderItem {
  item_id: number;
  item_name: string;
  quantity: number;
  price: number;
}

export default function VendorOrderPage() {
  const params = useParams()
  const router = useRouter()
  const vendor = params.vendor as string
  
  // Mock menu items (3 Subway items as requested)
  const menuItems: MenuItem[] = [
    {
      item_id: 1,
      item_name: "Italian B.M.T.",
      price: 8.99,
      description: "Pepperoni, salami, and ham"
    },
    {
      item_id: 2,
      item_name: "Turkey Breast",
      price: 7.99,
      description: "Oven roasted turkey breast"
    },
    {
      item_id: 3,
      item_name: "Veggie Delite",
      price: 6.99,
      description: "Fresh vegetables and cheese"
    }
  ]

  const [cart, setCart] = useState<OrderItem[]>([])
  const [dropoffLocation, setDropoffLocation] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  // Dropoff location options
  const dropoffLocations = [
    { value: '', label: 'Select a location' },
    { value: 'South 40', label: 'South 40' },
    { value: 'Olin', label: 'Olin' }
  ]

  // Add item to cart or increase quantity
  const addToCart = (menuItem: MenuItem) => {
    setCart(prevCart => {
      const existingItem = prevCart.find(item => item.item_id === menuItem.item_id)
      
      if (existingItem) {
        return prevCart.map(item =>
          item.item_id === menuItem.item_id
            ? { ...item, quantity: item.quantity + 1 }
            : item
        )
      } else {
        return [...prevCart, {
          item_id: menuItem.item_id,
          item_name: menuItem.item_name,
          quantity: 1,
          price: menuItem.price
        }]
      }
    })
  }

  // Remove item from cart
  const removeFromCart = (itemId: number) => {
    setCart(prevCart => prevCart.filter(item => item.item_id !== itemId))
  }

  // Update quantity
  const updateQuantity = (itemId: number, newQuantity: number) => {
    if (newQuantity <= 0) {
      removeFromCart(itemId)
      return
    }
    
    setCart(prevCart =>
      prevCart.map(item =>
        item.item_id === itemId
          ? { ...item, quantity: newQuantity }
          : item
      )
    )
  }

  // Calculate total
  const calculateTotal = () => {
    return cart.reduce((total, item) => total + (item.price * item.quantity), 0).toFixed(2)
  }

  // Submit order
  const handleSubmitOrder = async () => {
    if (cart.length === 0) {
      setError('Please add at least one item to your cart')
      return
    }

    if (!dropoffLocation.trim()) {
      setError('Please enter a dropoff location')
      return
    }

    setLoading(true)
    setError('')
    setSuccess('')

    try {
      // Prepare order data matching the protobuf structure
      const orderData = {
        // order_id will be generated by backend
        user_id: "placeholder-user-123", // TODO: Get from auth context/cookie
        vendor_id: vendor, // Using the vendor slug from URL
        items: cart,
        status: "pending", // Initial status
        // created_at will be set by backend
        dropoff_loc_id: dropoffLocation,
        robot_id: null // Will be assigned later by the system
      }

      const response = await fetch('/api/orders', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(orderData),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.message || 'Failed to create order')
      }

      setSuccess(`Order placed successfully! Order ID: ${data.order_id}, Redirecting to Order Page` )
      
      // Clear cart after successful order
      setTimeout(() => {
        setCart([])
        setDropoffLocation('')
        router.push(`/order/${data.order_id}`) // Redirect back to dashboard
      }, 2000)

    } catch (err: unknown) {
        if (err instanceof Error) {
                  setError(err.message || 'Failed to place order. Please try again.')

        }
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen" style={{ backgroundColor: '#E8D5FF' }}>
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="flex justify-between items-center h-20">
            <div className="flex items-center gap-4">
              <button 
                onClick={() => router.push('/dashboard')}
                className="text-purple-600 hover:text-purple-700 font-semibold"
              >
                ← Back to Dashboard
              </button>
              <h1 className="text-3xl font-bold text-black capitalize">{vendor}</h1>
            </div>
            <img 
              src="/WashU.png" 
              alt="WashU Logo" 
              className="h-10 w-auto"
            />
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Menu Items */}
          <div className="lg:col-span-2">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">Menu</h2>
            <div className="space-y-4">
              {menuItems.map((item) => (
                <div
                  key={item.item_id}
                  className="bg-white rounded-xl p-6 shadow-md border border-purple-200 hover:shadow-lg transition-shadow"
                >
                  <div className="flex justify-between items-start">
                    <div className="flex-1">
                      <h3 className="text-xl font-semibold text-gray-900 mb-2">
                        {item.item_name}
                      </h3>
                      <p className="text-gray-600 mb-3">{item.description}</p>
                      <p className="text-lg font-bold text-purple-600">
                        ${item.price.toFixed(2)}
                      </p>
                    </div>
                    <button
                      onClick={() => addToCart(item)}
                      className="bg-purple-600 hover:bg-purple-700 text-white font-semibold py-2 px-4 rounded-lg transition-colors"
                    >
                      Add to Cart
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Cart / Order Summary */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-xl p-6 shadow-md border border-purple-200 sticky top-6">
              <h2 className="text-2xl font-bold text-gray-900 mb-6">Your Order</h2>
              
              {error && (
                <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg mb-4">
                  {error}
                </div>
              )}
              
              {success && (
                <div className="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded-lg mb-4">
                  {success}
                </div>
              )}

              {cart.length === 0 ? (
                <p className="text-gray-500 text-center py-8">Your cart is empty</p>
              ) : (
                <div className="space-y-4 mb-6">
                  {cart.map((item) => (
                    <div key={item.item_id} className="flex justify-between items-center border-b border-gray-200 pb-3">
                      <div className="flex-1">
                        <p className="font-semibold text-gray-900">{item.item_name}</p>
                        <p className="text-sm text-gray-600">${item.price.toFixed(2)} each</p>
                      </div>
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => updateQuantity(item.item_id, item.quantity - 1)}
                          className="w-8 h-8 bg-gray-200 hover:bg-gray-300 rounded-full flex items-center justify-center font-bold"
                        >
                          -
                        </button>
                        <span className="w-8 text-center font-semibold">{item.quantity}</span>
                        <button
                          onClick={() => updateQuantity(item.item_id, item.quantity + 1)}
                          className="w-8 h-8 bg-gray-200 hover:bg-gray-300 rounded-full flex items-center justify-center font-bold"
                        >
                          +
                        </button>
                        <button
                          onClick={() => removeFromCart(item.item_id)}
                          className="ml-2 text-red-500 hover:text-red-700 font-bold"
                        >
                          ×
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Dropoff Location */}
              <div className="mb-6">
                <label htmlFor="dropoff" className="block text-sm font-semibold text-gray-700 mb-2">
                  Dropoff Location *
                </label>
                <select
                  id="dropoff"
                  value={dropoffLocation}
                  onChange={(e) => setDropoffLocation(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent bg-white"
                >
                  {dropoffLocations.map((location) => (
                    <option key={location.value} value={location.value}>
                      {location.label}
                    </option>
                  ))}
                </select>
              </div>

              {/* Total */}
              {cart.length > 0 && (
                <div className="border-t border-gray-200 pt-4 mb-6">
                  <div className="flex justify-between items-center text-xl font-bold">
                    <span>Total:</span>
                    <span className="text-purple-600">${calculateTotal()}</span>
                  </div>
                </div>
              )}

              {/* Submit Button */}
              <button
                onClick={handleSubmitOrder}
                disabled={loading || cart.length === 0}
                className={`w-full py-3 px-4 rounded-lg font-semibold text-white transition-colors ${
                  loading || cart.length === 0
                    ? 'bg-gray-400 cursor-not-allowed'
                    : 'bg-purple-600 hover:bg-purple-700'
                }`}
              >
                {loading ? 'Placing Order...' : 'Place Order'}
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
